#!/bin/sh
# This regression test is a part of SIPp.
# Author: Petr Cisar
. "`dirname "$0"`/../functions"; init

# uac.xml checks reception of regex-based responses
sippbg -sn uas -i 127.0.0.1 -p 5070 -m 1
sippbg -sf uac.xml -i 127.0.0.1 -m 1 127.0.0.1:5070
job2=$!

# If job2 did not finish, we have failure.
if /bin/kill -0 $job2 2>/dev/null; then
    fail
else
    ok
fi
