#!/bin/sh
# This regression test is a part of SIPp.
# The method of a response is that of its CSeq header, in any case, not
# of "CSeq" in another header or in the body.
. "`dirname "$0"`/../functions"; init

sippbg -sf uas.xml -i 127.0.0.1 -p 5396 -m 1 -timeout 6
sippfg -sf uac.xml -i 127.0.0.1 -p 5398 127.0.0.1:5396 -m 1 \
    -timeout 6 -timeout_error >/dev/null 2>&1
status=$?

if test $status -ne 0; then
    fail "UAC failed with $status"
else
    ok
fi
