# Config

language: cpp
sudo: false
dist: trusty
cache: bundler
notifications:
  email: false

# Build matrix (2x compiler, 1x confopts)
compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libpcap-dev
      - libsctp-dev
      - libncurses5-dev
      - libssl-dev
      - libgsl0-dev
      - valgrind

env:
  - CONFOPTS="--with-gsl --with-openssl --with-pcap --with-rtpstream --with-sctp"

# Extend build matrix
matrix:
  include:
    - os: linux
      compiler: gcc
      env: CONFOPTS="--with-openssl --without-pcap --without-rtpstream"
    - os: linux
      compiler: gcc
      env: CONFOPTS=""
    - os: linux
      compiler: gcc
      env: CONFOPTS="--disable-epoll"
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - g++-4.6
            - libpcap-dev
            - libsctp-dev
            - libncurses5-dev
            - libssl-dev
            - libgsl0-dev
            - valgrind
      env:
        - CC=gcc-4.6
        - CXX=g++-4.6
        - CONFOPTS="--with-gsl --with-openssl --with-pcap --with-rtpstream --with-sctp"
    - os: osx
      compiler: clang
      env: CONFOPTS="--with-gsl --with-openssl --with-pcap --with-rtpstream"

before_script:
  - autoreconf -vifs
  - if [ "$TRAVIS_OS_NAME" = osx ]; then brew install gsl; fi
  # 2016-10: Apple doesn't include openssl any more because of security
  # problems openssl had. Manually specify path to includes/libs.
  - if [ "$TRAVIS_OS_NAME" = osx ]; then brew install openssl; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then CPPFLAGS="-I/usr/local/opt/openssl/include"; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then LDFLAGS="-L/usr/local/opt/openssl/lib"; fi
  - ./configure CPPFLAGS=$CPPFLAGS LDFLAGS=$LDFLAGS $CONFOPTS

script:
  - make -j2
  - make -j2 check
  - if [ "$TRAVIS_OS_NAME" != osx ]; then TEST_SKIP_VALGRIND=1 ./regress/runtests; fi
  - ./validate-src.sh
