#!/bin/sh
# This regression test is a part of SIPp.
# Author: Walter Doekes, OSSO B.V., 2014
. "`dirname "$0"`/../functions"; init

skip "broken by 337f5c0cd"

tcplisten 5070 >tmp.log 2>&1 &
pid=$!
sleep 1
sippbg -m 1 -sn uac -i 127.0.3.1 -t t1 -p 5071 127.0.2.1:5070
/bin/kill -9 $pid 2>/dev/null

if grep -q '^Connection from 127.0.3.1:' tmp.log; then
    ok
else
    fail "broken by 337f5c0cd (?)"
fi
