#!/bin/sh
# This regression test is a part of SIPp.
# Author: Walter Doekes, OSSO B.V., 2016
#
# Test Record-Route and [routes].
#
. "`dirname "$0"`/../functions"; init

sippbg -sf uas.xml -p 5070 -trace_msg -message_file uas.log
sippfg -m 1 -sf uac.xml 127.0.0.1:5070 -trace_msg -message_file uac.log \
    -timeout 5 -timeout_error >/dev/null 2>&1
status=$?

test $status -ne 0 && fail "SIPp UAC job failed"

uac_route=`sed -e '/^ACK /,/^$/!d;/^Route:/!d;s/[[:cntrl:]]//g' uac.log`
uac_expected='^Route: <sip:[0-9.]*:2;lr>, <sip:[0-9.]*:3;lr>, <sip:[0-9.]*:5060;lr>'

uas_route=`sed -e '/^BYE /,/^$/!d;/^Route:/!d;s/[[:cntrl:]]//g' uas.log`
uas_expected='^Route: <sip:[0-9.]*:5060;lr>, <sip:[0-9.]*:3;lr>, <sip:[0-9.]*:2;lr>'

if ! echo "$uac_route" | grep -q "$uac_expected"; then
    fail "UAC Route unexpected, got: $uac_route"
elif ! echo "$uas_route" | grep -q "$uas_expected"; then
    fail "UAS Route unexpected, got: $uas_route"
else
    ok
fi
