/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "sipp-rpc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
getcallcounter_1(callcounter_t *argp, callcounter_t *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, GETCALLCOUNTER,
		(xdrproc_t) xdr_callcounter_t, (caddr_t) argp,
		(xdrproc_t) xdr_callcounter_t, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
enablelog4autoanswer_1(void *argp, bool_t *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, ENABLELOG4AUTOANSWER,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_bool, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
disablelog4autoanswer_1(void *argp, bool_t *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, DISABLELOG4AUTOANSWER,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_bool, (caddr_t) clnt_res,
		TIMEOUT));
}
