#!/bin/sh
. "`dirname "$0"`/../functions"; init

# BSD-netcat does not take -p when listening. Take input from /dev/zero
# so we stay alive instead of EOF.
nc -v -l 5070 >tmp.log 2>&1 </dev/zero &
sleep 1
sippbg -m 1 -sn uac -i 127.0.3.1 -t t1 -p 5071 127.0.2.1:5070

if grep -i 'connection.*accepted' tmp.log | grep -q '[^0-9]5071[^0-9]'; then
    unexpected_ok
else
    expected_fail
fi
