#!/bin/sh
# This regression test is a part of SIPp.
# The scenario options work with two dashes, as the others do: --sd,
# --sf, --sn, --rxsf, --rxsn, --oocsf and --oocsn.
. "`dirname "$0"`/../functions"; init

uac=`mktemp`; uas=`mktemp`; ooc=`mktemp`
trap 'rm -f "$uac" "$uas" "$ooc" err.log' EXIT

sippfg --sd uac >"$uac" 2>err.log
sippfg --sd uas >"$uas" 2>>err.log
sippfg --sd ooc_default >"$ooc" 2>>err.log
grep -q '<scenario name=' "$uac" || fail "--sd uac: `tail -n 1 err.log`"

sippbg -sn uas -i 127.0.0.1 -p 24480 -m 4
for opts in "--sf $uac --oocsf $ooc" "--sn uac --oocsn ooc_default" \
        "--sn uac --rxsf $uas" "--sn uac --rxsn uas"; do
    sippfg $opts -m 1 -i 127.0.0.1 -p 24481 127.0.0.1:24480 \
        -timeout 10 -timeout_error >/dev/null 2>err.log ||
        fail "$opts: `tail -n 1 err.log`"
done
ok
